name: 'Build and Notify' 
description: 'Composite action for building and notifying'

inputs:
  webhook-url:
    required: true
  error-mention-id:
    required: true
  error-mention-name:
    required: true
  success-mention-id:
    required: true
  success-mention-name:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get commit information
      id: commit_info
      run: |
        COMMIT_HASH=$(git rev-parse HEAD)
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        echo "::set-output name=commit_hash::$COMMIT_HASH"
        echo "::set-output name=branch_name::$BRANCH_NAME"

    - name: Determine job status
      id: job_status
      shell: bash
      run: |
        if [ -n "${{ steps.error }}" ]; then
          echo "::set-output name=status::FAIL ❌"
          echo "::set-output name=color::attention"
          echo "::set-output name=mentionedId::${{ inputs.error-mention-id }}"
          echo "::set-output name=mentionedName::${{ inputs.error-mention-name }}"
        else
          echo "::set-output name=status::PASS ✅"
          echo "::set-output name=color::good"
          echo "::set-output name=mentionedId::${{ inputs.success-mention-id }}"
          echo "::set-output name=mentionedName::${{ inputs.success-mention-name }}"
        fi

    - name: Send notification to Microsoft Teams
      shell: bash
      run: |
        # Get the GitHub workflow run URL
        JOB_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        # Get the commit information from previous step
        COMMIT_HASH=${{ steps.commit_info.outputs.commit_hash }}
        BRANCH_NAME=${{ steps.commit_info.outputs.branch_name }}
        
        # Get the repository URL
        REPO_URL="[${{ github.repository }}](${{ github.event.repository.html_url }})"
        
        # Get the build number
        BUILD_NUMBER="${{ github.run_number }}"
        
        # Get job status from previous step
        STATUS=${{ steps.job_status.outputs.status }}
        COLOR=${{ steps.job_status.outputs.color }}
        MENTIONED_ID=${{ steps.job_status.outputs.mentionedId }}
        MENTIONED_NAME=${{ steps.job_status.outputs.mentionedName }}
        
        # Generate the payload for the notification
        payload='{
          "type": "message",
          "attachments": [
            {
              "contentType": "application/vnd.microsoft.card.adaptive",
              "content": {
                "type": "AdaptiveCard",
                "body": [
                  {
                    "type": "TextBlock",
                    "text": "<at>'"$MENTIONED_NAME"'</at>",
                    "color": "'"$COLOR"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Job Name:** Build and Notify",
                    "color": "'"$COLOR"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Job URL:** [View Job]('"$JOB_URL"')",
                    "color": "'"$COLOR"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Status:** '"$STATUS"'",
                    "color": "'"$COLOR"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Repository URL:** '"$REPO_URL"'",
                    "color": "'"$COLOR"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Build Number:** '"$BUILD_NUMBER"'",
                    "color": "'"$COLOR"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Branch Name:** '"$BRANCH_NAME"'",
                    "color": "'"$COLOR"'"
                  },
                  {
                    "type": "TextBlock",
                    "text": "**Latest Commit:** '"$COMMIT_HASH"'",
                    "color": "'"$COLOR"'"
                  }
                ],
                "msteams": {
                  "entities": [
                    {
                      "type": "mention",
                      "text": "<at>'"$MENTIONED_NAME"'</at>",
                      "mentioned": {
                        "id": "'"$MENTIONED_ID"'",
                        "name": "'"$MENTIONED_NAME"'"
                      }
                    }
                  ]
                }
              }
            }
          ]
        }'
        
        # Send the payload to Microsoft Teams
        echo "$payload" | curl -X POST -H 'Content-Type: application/json' -d @- 'https://amdcloud.webhook.office.com/webhookb2/133d4f16-689b-4281-a94b-44725b948c77@3dd8961f-e488-4e60-8e11-a82d994e183d/IncomingWebhook/20c43fc799fd49e9813582813c638323/f9e22351-f1c9-494f-88c5-8e04accf2ffe'
