name: Simple Workflow
 
on:
  push:
    branches:
      - main
 
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash
        run: echo "Building"
        
      - name: Test
        shell: bash
        run: echo "Testing"
        
      - name: Error
        id: error_step
        shell: bash
        run: |
          echo "Error encountered, marking the job as failed."
          exit 1  # Exit with a failure status

      - name: Checkout repository
        if: always()
        uses: actions/checkout@v2
        
      - name: Notify Build Status
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          error-mention-id: ${{ secrets.ERROR_MENTION_ID }}
          error-mention-name: ${{ secrets.ERROR_MENTION_NAME }}
          success-mention-id: ${{ secrets.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ secrets.SUCCESS_MENTION_NAME }}
        env:
          JOB_STATUS: ${{ if(steps.error_step.outcome == 'failure', 'FAIL ❌', 'PASS ✅') }}
