name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        shell: bash
        run: echo "Building"

      - name: Test
        shell: bash
        run: echo "Testing"

      - name: Deploy
        shell: bash
        run: echo "Deploying"

      - name: Checkout repository
        uses: actions/checkout@v2

      # Use a separate step to capture the status of the job
      - name: Determine Job Status
        id: job_status
        run: |
          if [ ${{ failure() }} ]; then
            echo "::set-output name=status::FAIL"
          else
            echo "::set-output name=status::PASS"
          fi
        continue-on-error: true

      # Notify the build status based on the determined status
      - name: Notify Build Status
        if: always()
        uses: ./.github/actions/build_and_notify
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          error-mention-id: ${{ secrets.ERROR_MENTION_ID }}
          error-mention-name: ${{ secrets.ERROR_MENTION_NAME }}
          success-mention-id: ${{ secrets.SUCCESS_MENTION_ID }}
          success-mention-name: ${{ secrets.SUCCESS_MENTION_NAME }}
          status: ${{ steps.job_status.outputs.status }}
